apiVersion: v1
kind: Services
metadata:
  labels:
    app: squid-proxy-server
  name: squid-proxy-svc
  namespace: squid
spec:
  ports:
    - port: 3128
      targetPort: 3128
      protocol: TCP
      name: squid-proxy
  selector:
    app: squid-proxy-server
